package golang

import (
	"regexp"
	"strings"

	"github.com/iheeb1/lx/internal/engine"
)

var (
	// Second line of a Go traceback frame: "\t/path/file.go:12 +0x1a0".
	frameFileRe = regexp.MustCompile(`^\t(\S.*?\.(?:go|s|c)|\?\?|<autogenerated>):\d+(?: \+0x[0-9a-f]+)?$`)
	offsetRe    = regexp.MustCompile(` \+0x[0-9a-f]+$`)
	// GOROOT is recognized from frames in packages only GOROOT has.
	gorootRe = regexp.MustCompile(`^\t(/\S+?)/src/(?:runtime|testing|internal|sync|reflect)/[\w./-]+\.(?:go|s):\d+`)
	modRe    = regexp.MustCompile(`^\t(/\S+?/pkg/mod)/\S+@`)
	gHdrRe   = regexp.MustCompile(`^goroutine \d+(?: [^\[]*)? \[[^\]]*\]:$`)
)

// foldCrash condenses a panic / fatal error / timeout report: goroutine
// dumps are grouped by stack (engine.GroupGoroutines), single stacks have
// their library frames folded (engine.FoldStacks), and every frame drops
// what an agent cannot use: the +0x offsets and the raw argument words
// (printed as "(...)", Go's own notation for elided arguments). The panic
// message, the "running tests:" list and all application frames stay
// verbatim. GOROOT and the module cache are abbreviated with a legend.
func foldCrash(c *engine.Context, lines []string) []string {
	lines = append([]string(nil), lines...)
	for len(lines) > 0 && strings.TrimSpace(lines[len(lines)-1]) == "" {
		lines = lines[:len(lines)-1]
	}
	if g, ok := engine.GroupGoroutines(lines); ok {
		lines = g
	} else {
		lines = engine.FoldStacks(c, lines)
	}
	return tidyFrames(lines)
}

// foldCrashInTest folds traces printed inside a test's own output.
func foldCrashInTest(c *engine.Context, lines []string) []string {
	for _, ln := range lines {
		if gHdrRe.MatchString(ln) || frameFileRe.MatchString(ln) {
			return tidyFrames(engine.FoldStacks(c, lines))
		}
	}
	return lines
}

// tidyFrames strips offsets and argument words from traceback frames and
// abbreviates GOROOT / GOMODCACHE paths. Error-class lines are never
// rewritten.
func tidyFrames(lines []string) []string {
	goroot, modcache := "", ""
	for _, ln := range lines {
		if goroot == "" {
			if m := gorootRe.FindStringSubmatch(ln); m != nil {
				goroot = m[1]
			}
		}
		if modcache == "" {
			if m := modRe.FindStringSubmatch(ln); m != nil {
				modcache = m[1]
			}
		}
	}
	usedRoot, usedMod := false, false
	out := make([]string, len(lines))
	for i, ln := range lines {
		out[i] = ln
		if engine.IsError(ln) {
			continue
		}
		if frameFileRe.MatchString(ln) {
			ln = offsetRe.ReplaceAllString(ln, "")
			if goroot != "" && strings.HasPrefix(ln, "\t"+goroot+"/src/") {
				ln = "\t$GOROOT" + ln[1+len(goroot):]
				usedRoot = true
			} else if modcache != "" && strings.HasPrefix(ln, "\t"+modcache+"/") {
				ln = "\t$GOMODCACHE" + ln[1+len(modcache):]
				usedMod = true
			}
			out[i] = ln
			continue
		}
		if i+1 < len(lines) && frameFileRe.MatchString(lines[i+1]) && ln != "" && ln[0] != '\t' && ln[0] != ' ' {
			out[i] = elideArgs(ln)
		}
	}
	var legend []string
	if usedRoot {
		legend = append(legend, "$GOROOT="+goroot)
	}
	if usedMod {
		legend = append(legend, "$GOMODCACHE="+modcache)
	}
	if len(legend) > 0 {
		out = append(out, "[paths: "+strings.Join(legend, ", ")+"]")
	}
	return out
}

// elideArgs turns "pkg.(*T).M(0xc000012345, {0x1, 0x2})" into
// "pkg.(*T).M(...)". Lines that do not end in an argument list are returned
// unchanged, as are empty argument lists.
func elideArgs(ln string) string {
	if !strings.HasSuffix(ln, ")") || strings.HasPrefix(ln, "created by ") {
		return ln
	}
	depth := 0
	for i := len(ln) - 1; i >= 0; i-- {
		switch ln[i] {
		case ')':
			depth++
		case '(':
			depth--
			if depth == 0 {
				args := ln[i+1 : len(ln)-1]
				if args == "" || args == "..." {
					return ln
				}
				return ln[:i] + "(...)"
			}
		}
	}
	return ln
}
