package golang

import (
	"strings"

	"github.com/iheeb1/lx/internal/engine"
	"github.com/iheeb1/lx/internal/lazyre"
)

var (
	frameFileRe = lazyre.New(`^\t(\S.*?\.(?:go|s|c)|\?\?|<autogenerated>):\d+(?: \+0x[0-9a-f]+)?$`)
	offsetRe    = lazyre.New(` \+0x[0-9a-f]+$`)

	gorootRe = lazyre.New(`^\t(/\S+?)/src/(?:runtime|testing|internal|sync|reflect)/[\w./-]+\.(?:go|s):\d+`)
	modRe    = lazyre.New(`^\t(/\S+?/pkg/mod)/\S+@`)
	gHdrRe   = lazyre.New(`^goroutine \d+(?: [^\[]*)? \[[^\]]*\]:$`)
)

func foldCrash(c *engine.Context, lines []string) []string {
	lines = append([]string(nil), lines...)
	for len(lines) > 0 && strings.TrimSpace(lines[len(lines)-1]) == "" {
		lines = lines[:len(lines)-1]
	}
	if g, ok := engine.GroupGoroutines(lines); ok {
		lines = g
	} else {
		lines = engine.FoldStacks(c, lines)
	}
	return tidyFrames(lines)
}

func foldCrashInTest(c *engine.Context, lines []string) []string {
	for _, ln := range lines {
		if gHdrRe.MatchString(ln) || frameFileRe.MatchString(ln) {
			return tidyFrames(engine.FoldStacks(c, lines))
		}
	}
	return lines
}

func tidyFrames(lines []string) []string {
	goroot, modcache := "", ""
	for _, ln := range lines {
		if goroot == "" {
			if m := gorootRe.FindStringSubmatch(ln); m != nil {
				goroot = m[1]
			}
		}
		if modcache == "" {
			if m := modRe.FindStringSubmatch(ln); m != nil {
				modcache = m[1]
			}
		}
	}
	usedRoot, usedMod := false, false
	out := make([]string, len(lines))
	for i, ln := range lines {
		out[i] = ln
		if engine.IsError(ln) {
			continue
		}
		if frameFileRe.MatchString(ln) {
			ln = offsetRe.ReplaceAllString(ln, "")
			if goroot != "" && strings.HasPrefix(ln, "\t"+goroot+"/src/") {
				ln = "\t$GOROOT" + ln[1+len(goroot):]
				usedRoot = true
			} else if modcache != "" && strings.HasPrefix(ln, "\t"+modcache+"/") {
				ln = "\t$GOMODCACHE" + ln[1+len(modcache):]
				usedMod = true
			}
			out[i] = ln
			continue
		}
		if i+1 < len(lines) && frameFileRe.MatchString(lines[i+1]) && ln != "" && ln[0] != '\t' && ln[0] != ' ' {
			out[i] = elideArgs(ln)
		}
	}
	var legend []string
	if usedRoot {
		legend = append(legend, "$GOROOT="+goroot)
	}
	if usedMod {
		legend = append(legend, "$GOMODCACHE="+modcache)
	}
	if len(legend) > 0 {
		out = append(out, "[paths: "+strings.Join(legend, ", ")+"]")
	}
	return out
}

func elideArgs(ln string) string {
	if !strings.HasSuffix(ln, ")") || strings.HasPrefix(ln, "created by ") {
		return ln
	}
	depth := 0
	for i := len(ln) - 1; i >= 0; i-- {
		switch ln[i] {
		case ')':
			depth++
		case '(':
			depth--
			if depth == 0 {
				args := ln[i+1 : len(ln)-1]
				if args == "" || args == "..." {
					return ln
				}
				return ln[:i] + "(...)"
			}
		}
	}
	return ln
}
