package engine

import (
	"fmt"
	"github.com/iheeb1/lx/internal/lazyre"
	"slices"
	"strconv"
	"strings"
)

var (
	pyFrameRe = lazyre.New(`^\s*File "[^"]+", line \d+(?:, in .+)?$`)

	goFileRe = lazyre.New(`^\t(?:\S.*?\.(?:go|s|c)|\?\?|<autogenerated>):\d+(?: \+0x[0-9a-f]+)?$`)

	atFrameRe = lazyre.New(`^\s*at\s+\S`)
	atJSRe    = lazyre.New(`^\s*at\s+(?:.*\((?:.+?:\d+(?::\d+)?|native|<anonymous>|index \d+)\)|(?:async\s+)?\S+:\d+(?::\d+)?|<anonymous>|native)\s*\{?$`)
	atJavaRe  = lazyre.New(`^\s*at\s+[\w$./<>\[\]-]+\([^()]*\)(?: ~?\[[^\]]*\])?$`)
	atNetRe   = lazyre.New(`^\s*at\s+.+\(.*\)(?: in .+:line \d+)?$`)

	rustNumRe = lazyre.New(`^\s*\d+: (?:0x[0-9a-f]+ - )?(\S+)`)
	rustAtRe  = lazyre.New(`^\s+at \S.*:\d+(?::\d+)?$`)

	rubyRe = lazyre.New("^\\s*(?:from )?\\S+?\\.rb:\\d+:in [`'][^`']*'$")

	phpRe = lazyre.New(`^\s*#\d+ (?:\S+\(\d+\): .*|\{main\}|\[internal function\]: .*)$`)

	stackFillerRe = lazyre.New(`^\s*(?:\.\.\. \d+ (?:more|common frames omitted)` +
		`|\.\.\.additional frames elided\.\.\.` +
		`|\[Previous line repeated \d+ more times?\]` +
		`|--- End of (?:inner exception )?stack trace(?: from previous location)?(?: where exception was thrown)? ---)$`)

	runSuffixRe = lazyre.New(` \[×(\d+)\]$`)
)

type libPattern struct {
	re    *lazyre.Regexp
	label string
}

var libPatterns = []libPattern{
	{lazyre.New(`node_modules/((?:@[^/\s]+/)?[^/\s:)]+)`), ""},
	{lazyre.New(`\(?\b(node:[a-z_]+)`), ""},
	{lazyre.New(`[\s(]internal/[\w/.-]+\.js:\d`), "node:internal"},

	{lazyre.New(`\((?:native|<anonymous>|index \d+)\)\s*\{?$|^\s*at\s+(?:<anonymous>|native)\s*$`), "js-runtime"},
	{lazyre.New(`\b(?:ext|deno):\w`), "deno"},

	{lazyre.New(`(?:site|dist)-packages/([^/"]+?)(?:\.py)?[/"]`), ""},
	{lazyre.New(`/lib/python\d(?:\.\d+)?/([^/"]+?)(?:\.py)?[/"]`), ""},
	{lazyre.New(`<frozen (\w+)`), ""},

	{lazyre.New(`/pkg/mod/([^@\s]+)@`), ""},

	{lazyre.New(`/(?:libexec|go|golang|goroot|go\d[\w.]*|go-\d[\w.]*)/src/([a-z0-9_]+(?:/[\w.-]+)*)/[\w.-]+\.(?:go|s):\d`), ""},
	{lazyre.New(`(?m)^\t_testmain\.go:`), "testing"},
	{lazyre.New(`(?m)^\t<autogenerated>:`), "runtime"},

	{lazyre.New(`at\s+(?:[\w.$-]+/)?((?:java|javax|jdk|sun|com\.sun|kotlin|kotlinx|scala|org\.junit|junit|org\.apache|org\.springframework|org\.gradle|org\.hibernate|io\.netty|org\.eclipse|com\.google|reactor|io\.reactivex|org\.testng|org\.mockito|groovy|org\.codehaus|worker\.org\.gradle|com\.intellij)\.[\w$]+)`), ""},

	{lazyre.New(`at\s+((?:System|Microsoft|Xunit|NUnit)\.[\w]+)`), ""},

	{lazyre.New(`/rustc/[0-9a-f]+/library/(\w+)`), ""},
	{lazyre.New(`\.cargo/registry/src/[^/]+/([A-Za-z0-9_-]+?)-\d`), ""},
	{lazyre.New(`^\s*\d+: (?:0x[0-9a-f]+ - )?((?:std|core|alloc|tokio|futures|hyper|tower|axum)::|rust_begin_unwind|__rust|_start|__libc_start|start_thread|clone3?$)`), "std"},

	{lazyre.New(`/gems/(?:[^/]+/)*?([A-Za-z0-9_-]+?)-\d[\w.]*/`), ""},
	{lazyre.New(`/lib/ruby/\d|<internal:`), "ruby"},

	{lazyre.New(`/vendor/([\w.-]+/[\w.-]+)/`), ""},
	{lazyre.New(`\[internal function\]`), "php"},

	{lazyre.New(`(?:^|[\s(])/usr/(?:local/)?lib\d*/`), "system"},
}

type stackFrame struct {
	start, end int
	filler     bool
	lib        bool
	root       string
	weight     int
	keep       bool
	topDown    bool
	pinned     bool
	focus      uint64
}

func FoldStacks(c *Context, lines []string) []string {
	cwd := ""
	if c != nil && c.Cwd != "" && c.Cwd != "/" {
		cwd = strings.TrimRight(c.Cwd, "/") + "/"
	}
	out := make([]string, 0, len(lines))
	for i := 0; i < len(lines); {
		f, ok := parseFrame(lines, i)
		if !ok || f.filler {
			out = append(out, lines[i])
			i++
			continue
		}

		trace := []stackFrame{f}
		j := f.end
		for j < len(lines) {
			g, ok := parseFrame(lines, j)
			if !ok {
				break
			}
			trace = append(trace, g)
			j = g.end
		}
		out = append(out, foldTrace(lines, trace, cwd, modeOf(c).knobs().boundary, c.focus())...)
		i = j
	}
	return out
}

const maxFrameLen = 2000

func parseFrame(lines []string, i int) (stackFrame, bool) {
	if len(lines[i]) > maxFrameLen {
		return stackFrame{}, false
	}
	ln, w := splitRunSuffix(lines[i])
	f := stackFrame{start: i, end: i + 1, weight: w, topDown: true}
	switch {
	case stackFillerRe.MatchString(ln):
		f.filler = true
		return f, true
	case pyFrameRe.MatchString(ln):
		f.topDown = false
		ind := len(leadingSpace(ln))
		j := i + 1
		for j < len(lines) {
			nx := lines[j]
			if strings.TrimSpace(nx) == "" || len(leadingSpace(nx)) <= ind || pyFrameRe.MatchString(nx) {
				break
			}
			j++
		}
		f.end = j
		return f, true
	case atFrameRe.MatchString(ln):
		if atJSRe.MatchString(ln) || atJavaRe.MatchString(ln) || atNetRe.MatchString(ln) {
			return f, true
		}
		return f, false
	case phpRe.MatchString(ln), strings.Contains(ln, ".rb:") && rubyRe.MatchString(ln):
		return f, true
	}

	if ln != "" && ln[0] != ' ' && ln[0] != '\t' && i+1 < len(lines) && goFileRe.MatchString(lines[i+1]) &&
		(strings.HasSuffix(ln, ")") || strings.HasPrefix(ln, "created by ")) {
		f.end = i + 2
		return f, true
	}

	if m := rustNumRe.FindStringSubmatch(ln); m != nil && looksRustSymbol(m[1]) {
		j := i + 1
		for j < len(lines) && rustAtRe.MatchString(lines[j]) {
			j++
		}
		f.end = j
		return f, true
	}
	return f, false
}

func splitRunSuffix(ln string) (string, int) {
	if !strings.HasSuffix(ln, "]") || !strings.Contains(ln, " [×") {
		return ln, 1
	}
	m := runSuffixRe.FindStringSubmatchIndex(ln)
	if m == nil {
		return ln, 1
	}
	n, err := strconv.Atoi(ln[m[2]:m[3]])
	if err != nil || n < 1 {
		n = 1
	}
	return ln[:m[0]], n
}

func looksRustSymbol(s string) bool {
	return strings.Contains(s, "::") || s == "rust_begin_unwind" || s == "<unknown>" ||
		strings.HasPrefix(s, "__rust") || strings.HasPrefix(s, "_start") || strings.HasPrefix(s, "__libc")
}

func classifyFrame(lines []string, f *stackFrame, cwd string) {
	text := lines[f.start]
	if f.end-f.start > 1 && !pyFrameRe.MatchString(text) {
		text = strings.Join(lines[f.start:f.end], "\n")
	}
	vendored := strings.Contains(text, "node_modules/") || strings.Contains(text, "-packages/") ||
		strings.Contains(text, "/vendor/") || strings.Contains(text, "/pkg/mod/")
	if cwd != "" && strings.Contains(text, cwd) && !vendored {
		return
	}
	for _, p := range libPatterns {
		m := p.re.FindStringSubmatch(text)
		if m == nil {
			continue
		}
		f.lib = true
		f.root = p.label
		if len(m) > 1 && m[1] != "" {
			f.root = strings.TrimSuffix(m[1], "::")
		}
		if f.root == "" {
			f.root = "lib"
		}
		return
	}
}

const minFoldFrames = 6

func foldTrace(lines []string, trace []stackFrame, cwd string, boundary int, fm *focusMatcher) []string {
	frames := 0
	for _, f := range trace {
		if !f.filler {
			frames++
		}
	}
	if frames <= minFoldFrames {
		return append([]string(nil), lines[trace[0].start:trace[len(trace)-1].end]...)
	}
	focused := false
	for k := range trace {
		f := &trace[k]
		if f.filler {
			continue
		}
		classifyFrame(lines, f, cwd)
		for _, ln := range lines[f.start:f.end] {
			if bare, _ := splitRunSuffix(ln); IsError(ln) || strings.HasSuffix(strings.TrimSpace(bare), "{") {
				f.pinned = true
			}
		}
		if f.lib && fm != nil {
			f.focus = fm.files(strings.Join(lines[f.start:f.end], "\n"))
			focused = focused || f.focus != 0
		}
	}
	markFrames(trace, boundary, false)
	if !focused {
		return renderTrace(lines, trace)
	}
	base := renderTrace(lines, trace)
	var hits []focusHit
	for _, f := range trace {
		if f.focus == 0 || f.keep {
			continue
		}
		for _, ln := range lines[f.start:f.end] {
			if fm.files(ln) != 0 {
				hits = append(hits, newFocusHit(ln, f.focus))
				break
			}
		}
	}
	markFrames(trace, boundary, true)
	out := renderTrace(lines, trace)
	if !slices.Equal(out, base) {
		fm.hits = append(fm.hits, hits...)
	}
	return out
}

func markFrames(trace []stackFrame, boundary int, focus bool) {
	app := func(f stackFrame) bool { return !f.filler && (!f.lib || focus && f.focus != 0) }
	first, last := -1, -1
	for k := range trace {
		f := &trace[k]
		f.keep = f.filler || f.pinned || app(*f)
		if !f.filler {
			if first < 0 {
				first = k
			}
			last = k
		}
	}
	if trace[first].topDown {
		trace[first].keep = true
	} else {
		trace[last].keep = true
	}

	for k, f := range trace {
		if !app(f) {
			continue
		}
		for _, d := range []int{-1, 1} {
			for s := 1; s <= boundary; s++ {
				if n := k + d*s; n >= 0 && n < len(trace) && !trace[n].filler {
					trace[n].keep = true
				}
			}
		}
	}
}

func renderTrace(lines []string, trace []stackFrame) []string {
	var out []string
	for k := 0; k < len(trace); {
		if trace[k].keep {
			out = append(out, lines[trace[k].start:trace[k].end]...)
			k++
			continue
		}
		e := k
		for e < len(trace) && !trace[e].keep {
			e++
		}
		if e-k < 2 {
			out = append(out, lines[trace[k].start:trace[k].end]...)
			k++
			continue
		}
		n := 0
		var roots []string
		seen := map[string]bool{}
		for _, f := range trace[k:e] {
			n += f.weight
			if !seen[f.root] {
				seen[f.root] = true
				roots = append(roots, f.root)
			}
		}
		if len(roots) > 3 {
			roots = append(roots[:3], "…")
		}
		out = append(out, fmt.Sprintf("%s… %d library frames (%s)", leadingSpace(lines[trace[k].start]), n, strings.Join(roots, ", ")))
		k = e
	}
	return out
}
