package engine

import (
	"fmt"
	"github.com/iheeb1/lx/internal/lazyre"
	"strconv"
	"strings"
)

// Stack trace folding.
//
// A trace is a maximal run of consecutive frames. Frames are recognized for
// Node/JS, Python, Go, Java/Kotlin, .NET, Rust, Ruby and PHP. Message lines
// ("Error: …", "Caused by: …", "ValueError: …") are never frames, so they end
// a trace and are never touched.

var (
	// Python: `  File "x.py", line 12, in f` followed by source and ^^^ lines.
	pyFrameRe = lazyre.New(`^\s*File "[^"]+", line \d+(?:, in .+)?$`)
	// Go: the second line of a frame, `\t/path/file.go:12 +0x1a0`.
	goFileRe = lazyre.New(`^\t(?:\S.*?\.(?:go|s|c)|\?\?|<autogenerated>):\d+(?: \+0x[0-9a-f]+)?$`)
	// JS / Java / .NET / Rust-location frames all start with "at".
	atFrameRe = lazyre.New(`^\s*at\s+\S`)
	atJSRe    = lazyre.New(`^\s*at\s+(?:.*\((?:.+?:\d+(?::\d+)?|native|<anonymous>|index \d+)\)|(?:async\s+)?\S+:\d+(?::\d+)?|<anonymous>|native)\s*\{?$`)
	atJavaRe  = lazyre.New(`^\s*at\s+[\w$./<>\[\]-]+\([^()]*\)(?: ~?\[[^\]]*\])?$`)
	atNetRe   = lazyre.New(`^\s*at\s+.+\(.*\)(?: in .+:line \d+)?$`)
	// Rust: `   3: myapp::main` then `             at ./src/main.rs:4:5`.
	rustNumRe = lazyre.New(`^\s*\d+: (?:0x[0-9a-f]+ - )?(\S+)`)
	rustAtRe  = lazyre.New(`^\s+at \S.*:\d+(?::\d+)?$`)
	// Ruby: `from /x/y.rb:12:in 'm'` (first line carries the message: not a frame).
	rubyRe = lazyre.New("^\\s*(?:from )?\\S+?\\.rb:\\d+:in [`'][^`']*'$")
	// PHP: `#3 /var/www/x.php(12): Foo->bar()` / `#4 {main}`.
	phpRe = lazyre.New(`^\s*#\d+ (?:\S+\(\d+\): .*|\{main\}|\[internal function\]: .*)$`)
	// Filler lines that belong to a trace but are not frames.
	stackFillerRe = lazyre.New(`^\s*(?:\.\.\. \d+ (?:more|common frames omitted)` +
		`|\.\.\.additional frames elided\.\.\.` +
		`|\[Previous line repeated \d+ more times?\]` +
		`|--- End of (?:inner exception )?stack trace(?: from previous location)?(?: where exception was thrown)? ---)$`)
	// Suffix added by CollapseRuns to repeated identical lines.
	runSuffixRe = lazyre.New(` \[×(\d+)\]$`)
)

// libPattern marks a frame as library/runtime code; the first capture group
// (if any) names the root shown in the fold marker, otherwise label is used.
type libPattern struct {
	re    *lazyre.Regexp
	label string
}

var libPatterns = []libPattern{
	// JavaScript.
	{lazyre.New(`node_modules/((?:@[^/\s]+/)?[^/\s:)]+)`), ""},
	{lazyre.New(`\(?\b(node:[a-z_]+)`), ""},
	{lazyre.New(`[\s(]internal/[\w/.-]+\.js:\d`), "node:internal"},
	// Frames with no source location: engine internals, not app code.
	{lazyre.New(`\((?:native|<anonymous>|index \d+)\)\s*\{?$|^\s*at\s+(?:<anonymous>|native)\s*$`), "js-runtime"},
	{lazyre.New(`\b(?:ext|deno):\w`), "deno"},
	// Python.
	{lazyre.New(`(?:site|dist)-packages/([^/"]+?)(?:\.py)?[/"]`), ""},
	{lazyre.New(`/lib/python\d(?:\.\d+)?/([^/"]+?)(?:\.py)?[/"]`), ""},
	{lazyre.New(`<frozen (\w+)`), ""},
	// Go: module cache, GOROOT (homebrew libexec, /usr/local/go, …).
	{lazyre.New(`/pkg/mod/([^@\s]+)@`), ""},
	// The first segment after src/ has no dot, which excludes GOPATH-mode
	// application paths like ~/go/src/github.com/me/app.
	{lazyre.New(`/(?:libexec|go|golang|goroot|go\d[\w.]*|go-\d[\w.]*)/src/([a-z0-9_]+(?:/[\w.-]+)*)/[\w.-]+\.(?:go|s):\d`), ""},
	{lazyre.New(`(?m)^\t_testmain\.go:`), "testing"},
	{lazyre.New(`(?m)^\t<autogenerated>:`), "runtime"},
	// JVM.
	{lazyre.New(`at\s+(?:[\w.$-]+/)?((?:java|javax|jdk|sun|com\.sun|kotlin|kotlinx|scala|org\.junit|junit|org\.apache|org\.springframework|org\.gradle|org\.hibernate|io\.netty|org\.eclipse|com\.google|reactor|io\.reactivex|org\.testng|org\.mockito|groovy|org\.codehaus|worker\.org\.gradle|com\.intellij)\.[\w$]+)`), ""},
	// .NET.
	{lazyre.New(`at\s+((?:System|Microsoft|Xunit|NUnit)\.[\w]+)`), ""},
	// Rust.
	{lazyre.New(`/rustc/[0-9a-f]+/library/(\w+)`), ""},
	{lazyre.New(`\.cargo/registry/src/[^/]+/([A-Za-z0-9_-]+?)-\d`), ""},
	{lazyre.New(`^\s*\d+: (?:0x[0-9a-f]+ - )?((?:std|core|alloc|tokio|futures|hyper|tower|axum)::|rust_begin_unwind|__rust|_start|__libc_start|start_thread|clone3?$)`), "std"},
	// Ruby.
	{lazyre.New(`/gems/(?:[^/]+/)*?([A-Za-z0-9_-]+?)-\d[\w.]*/`), ""},
	{lazyre.New(`/lib/ruby/\d|<internal:`), "ruby"},
	// PHP.
	{lazyre.New(`/vendor/([\w.-]+/[\w.-]+)/`), ""},
	{lazyre.New(`\[internal function\]`), "php"},
	// System libraries.
	{lazyre.New(`(?:^|[\s(])/usr/(?:local/)?lib\d*/`), "system"},
}

// stackFrame is one frame (or filler line group) of a trace.
type stackFrame struct {
	start, end int // line range [start, end)
	filler     bool
	lib        bool
	root       string
	weight     int  // frames represented (CollapseRuns ×N)
	keep       bool // must stay visible
	topDown    bool // false for Python (most recent call last)
}

// FoldStacks shortens stack traces in lines while keeping everything a reader
// needs to locate a failure. It recognizes Node/JS, Python, Go, Java/Kotlin
// (incl. "... N more"), .NET, Rust, Ruby and PHP frames. In every trace of
// more than 6 frames it keeps the throw site (first frame; last frame for
// Python), every application frame, every library frame adjacent to an
// application frame (the boundary), every frame containing an error-class
// line, and folds each remaining run of 2+ consecutive library/runtime frames
// into one line:
//
//	<indent>… N library frames (supertest, node:events, node:net)
//
// listing up to 3 distinct roots (package, module or runtime area). Frames
// are "library" when their location is under node_modules, node:*,
// site-packages, the Python stdlib, GOROOT or the Go module cache, a JVM/.NET
// platform or test-framework package, Rust std / cargo registry, gems or PHP
// vendor/ — unless the path is under c.Cwd outside such directories.
// Message lines are never touched and no other line is changed. c may be nil.
// The input slice is not modified.
func FoldStacks(c *Context, lines []string) []string {
	cwd := ""
	if c != nil && c.Cwd != "" && c.Cwd != "/" {
		cwd = strings.TrimRight(c.Cwd, "/") + "/"
	}
	out := make([]string, 0, len(lines))
	for i := 0; i < len(lines); {
		f, ok := parseFrame(lines, i)
		if !ok || f.filler {
			out = append(out, lines[i])
			i++
			continue
		}
		// Collect the whole trace.
		trace := []stackFrame{f}
		j := f.end
		for j < len(lines) {
			g, ok := parseFrame(lines, j)
			if !ok {
				break
			}
			trace = append(trace, g)
			j = g.end
		}
		out = append(out, foldTrace(lines, trace, cwd)...)
		i = j
	}
	return out
}

// parseFrame recognizes the frame starting at lines[i].
// maxFrameLen: no real frame line is longer; skipping longer lines keeps
// FoldStacks linear-time cheap on minified output.
const maxFrameLen = 2000

func parseFrame(lines []string, i int) (stackFrame, bool) {
	if len(lines[i]) > maxFrameLen {
		return stackFrame{}, false
	}
	ln, w := splitRunSuffix(lines[i])
	f := stackFrame{start: i, end: i + 1, weight: w, topDown: true}
	switch {
	case stackFillerRe.MatchString(ln):
		f.filler = true
		return f, true
	case pyFrameRe.MatchString(ln):
		f.topDown = false
		ind := len(leadingSpace(ln))
		j := i + 1
		for j < len(lines) {
			nx := lines[j]
			if strings.TrimSpace(nx) == "" || len(leadingSpace(nx)) <= ind || pyFrameRe.MatchString(nx) {
				break
			}
			j++
		}
		f.end = j
		return f, true
	case atFrameRe.MatchString(ln):
		if atJSRe.MatchString(ln) || atJavaRe.MatchString(ln) || atNetRe.MatchString(ln) {
			return f, true
		}
		return f, false
	case phpRe.MatchString(ln), strings.Contains(ln, ".rb:") && rubyRe.MatchString(ln):
		return f, true
	}
	// Go: function line (not indented) followed by a tab-indented file line.
	if ln != "" && ln[0] != ' ' && ln[0] != '\t' && i+1 < len(lines) && goFileRe.MatchString(lines[i+1]) &&
		(strings.HasSuffix(ln, ")") || strings.HasPrefix(ln, "created by ")) {
		f.end = i + 2
		return f, true
	}
	// Rust: numbered symbol line with a Rust-looking symbol, then "at" lines.
	if m := rustNumRe.FindStringSubmatch(ln); m != nil && looksRustSymbol(m[1]) {
		j := i + 1
		for j < len(lines) && rustAtRe.MatchString(lines[j]) {
			j++
		}
		f.end = j
		return f, true
	}
	return f, false
}

// splitRunSuffix removes a CollapseRuns " [×N]" suffix, returning N (1 when
// there is none).
func splitRunSuffix(ln string) (string, int) {
	if !strings.HasSuffix(ln, "]") || !strings.Contains(ln, " [×") {
		return ln, 1
	}
	m := runSuffixRe.FindStringSubmatchIndex(ln)
	if m == nil {
		return ln, 1
	}
	n, err := strconv.Atoi(ln[m[2]:m[3]])
	if err != nil || n < 1 {
		n = 1
	}
	return ln[:m[0]], n
}

func looksRustSymbol(s string) bool {
	return strings.Contains(s, "::") || s == "rust_begin_unwind" || s == "<unknown>" ||
		strings.HasPrefix(s, "__rust") || strings.HasPrefix(s, "_start") || strings.HasPrefix(s, "__libc")
}

// classifyFrame sets lib/root for a frame.
func classifyFrame(lines []string, f *stackFrame, cwd string) {
	text := lines[f.start]
	if f.end-f.start > 1 && !pyFrameRe.MatchString(text) {
		// Go and Rust frames carry the location on the following line(s).
		text = strings.Join(lines[f.start:f.end], "\n")
	}
	vendored := strings.Contains(text, "node_modules/") || strings.Contains(text, "-packages/") ||
		strings.Contains(text, "/vendor/") || strings.Contains(text, "/pkg/mod/")
	if cwd != "" && strings.Contains(text, cwd) && !vendored {
		return // application code under the working directory
	}
	for _, p := range libPatterns {
		m := p.re.FindStringSubmatch(text)
		if m == nil {
			continue
		}
		f.lib = true
		f.root = p.label
		if len(m) > 1 && m[1] != "" {
			f.root = strings.TrimSuffix(m[1], "::")
		}
		if f.root == "" {
			f.root = "lib"
		}
		return
	}
}

// minFoldFrames: traces with this many frames or fewer are left alone.
const minFoldFrames = 6

func foldTrace(lines []string, trace []stackFrame, cwd string) []string {
	frames := 0
	for _, f := range trace {
		if !f.filler {
			frames++
		}
	}
	emitAll := func() []string {
		return append([]string(nil), lines[trace[0].start:trace[len(trace)-1].end]...)
	}
	if frames <= minFoldFrames {
		return emitAll()
	}
	for k := range trace {
		f := &trace[k]
		if f.filler {
			f.keep = true
			continue
		}
		classifyFrame(lines, f, cwd)
		for _, ln := range lines[f.start:f.end] {
			if bare, _ := splitRunSuffix(ln); IsError(ln) || strings.HasSuffix(strings.TrimSpace(bare), "{") {
				f.keep = true // error-class content, or opens a JS error-props block
			}
		}
		if !f.lib {
			f.keep = true
		}
	}
	// Throw site: first frame, or last frame for "most recent call last".
	first, last := -1, -1
	for k, f := range trace {
		if !f.filler {
			if first < 0 {
				first = k
			}
			last = k
		}
	}
	if trace[first].topDown {
		trace[first].keep = true
	} else {
		trace[last].keep = true
	}
	// Boundary: library frames adjacent to application frames.
	for k, f := range trace {
		if f.filler || f.lib {
			continue
		}
		for _, d := range []int{-1, 1} {
			if n := k + d; n >= 0 && n < len(trace) && !trace[n].filler {
				trace[n].keep = true
			}
		}
	}
	var out []string
	for k := 0; k < len(trace); {
		if trace[k].keep {
			out = append(out, lines[trace[k].start:trace[k].end]...)
			k++
			continue
		}
		e := k
		for e < len(trace) && !trace[e].keep {
			e++
		}
		if e-k < 2 {
			out = append(out, lines[trace[k].start:trace[k].end]...)
			k++
			continue
		}
		n := 0
		var roots []string
		seen := map[string]bool{}
		for _, f := range trace[k:e] {
			n += f.weight
			if !seen[f.root] {
				seen[f.root] = true
				roots = append(roots, f.root)
			}
		}
		if len(roots) > 3 {
			roots = append(roots[:3], "…")
		}
		out = append(out, fmt.Sprintf("%s… %d library frames (%s)", leadingSpace(lines[trace[k].start]), n, strings.Join(roots, ", ")))
		k = e
	}
	return out
}
