package hook_test

import (
	"strings"
	"testing"

	"github.com/iheeb1/lx/internal/hook"
)

var runnerRows = []struct {
	cmd  string
	want bool
	why  string
}{

	{"just test", true, "a test recipe"},
	{"just lint", true, "a lint recipe"},
	{"just typecheck", true, "a typecheck recipe"},
	{"just build", true, "a build recipe"},
	{"just check", true, "a check recipe"},
	{"just test-unit", true, "test-unit"},
	{"just backend::test", true, "a recipe in a module"},
	{"just -f ci.just test", true, "-f takes a value"},
	{"just --justfile=ci.just --working-directory . test", true, "value options"},
	{"just --set version 1.2 build", true, "--set NAME VALUE"},
	{"just VERSION=1 test", true, "an override before the recipe"},
	{"just test ./pkg/...", true, "a recipe argument (a path)"},
	{"just test tests/test_server.py", true, "a path argument is not a recipe name"},
	{"just lint test", true, "two check recipes"},
	{"just -q test", true, "quiet"},
	{"just", false, "the default recipe: unknown"},
	{"just dev", false, "a dev server"},
	{"just serve", false, "a server"},
	{"just watch", false, "a watcher"},
	{"just test-watch", false, "a watching test recipe"},
	{"just build serve", false, "a second recipe that serves"},
	{"just test deploy", false, "a second recipe that deploys"},
	{"just deploy", false, "deploys: may prompt"},
	{"just release", false, "releases: may prompt"},
	{"just test --watch", false, "watch flag handed to the recipe"},
	{"just test -w", false, "-w handed to the recipe"},
	{"just --list", false, "lists recipes"},
	{"just -l", false, "lists recipes"},
	{"just --choose", false, "an interactive picker"},
	{"just --show test", false, "prints the recipe"},
	{"just --dry-run test", false, "prints the commands"},
	{"just -n test", false, "prints the commands"},
	{"just --evaluate", false, "prints variables"},
	{"just --summary", false, "lists recipes"},
	{"just --fmt --check", false, "formats the justfile"},
	{"just --command ls", false, "runs an arbitrary command"},
	{"just shell", false, "a shell"},
	{"just db", false, "a database console"},

	{"task test", true, "a test task"},
	{"task lint", true, "a lint task"},
	{"task test:unit", true, "a namespaced task"},
	{"task lint test", true, "two check tasks"},
	{"task -d backend test", true, "--dir takes a value"},
	{"task --taskfile=ci.yml build", true, "attached value"},
	{"task -p lint typecheck", true, "parallel"},
	{"task test -- -run TestX", true, "CLI_ARGS"},
	{"task test COVER=1", true, "a variable"},
	{"task", false, "the default task: unknown"},
	{"task --list", false, "lists tasks"},
	{"task -l", false, "lists tasks"},
	{"task -a", false, "lists tasks"},
	{"task --summary test", false, "prints the task's summary"},
	{"task --dry test", false, "prints the commands"},
	{"task -n test", false, "prints the commands"},
	{"task --watch test", false, "watch mode"},
	{"task -w test", false, "watch mode"},
	{"task test -- --watch", false, "watch flag in CLI_ARGS"},
	{"task lint deploy", false, "a deploy task"},
	{"task dev", false, "a dev server"},
	{"task --status test", false, "exits with the task's up-to-date status"},
	{"task --json --list", false, "JSON"},
	{"task add buy milk", false, "Taskwarrior: not a check task"},
	{"task list", false, "Taskwarrior: not a check task"},

	{"mise run test", true, "a test task"},
	{"mise r lint", true, "r is run"},
	{"mise run test:unit", true, "a namespaced task"},
	{"mise run test ::: lint", true, "two check tasks"},
	{"mise run -j 4 test", true, "--jobs takes a value"},
	{"mise -C backend run test", true, "a global value option"},
	{"mise run test --coverage", true, "an argument handed to the task"},
	{"mise run", false, "no task: mise asks which one"},
	{"mise run dev", false, "a dev server"},
	{"mise run test ::: serve", false, "a second task that serves"},
	{"mise run --raw test", false, "--raw hands the terminal to the task"},
	{"mise run -r test", false, "--raw hands the terminal to the task"},
	{"mise run --dry-run test", false, "prints the commands"},
	{"mise run test --watch", false, "watch flag handed to the task"},
	{"mise watch test", false, "mise watch re-runs forever"},
	{"mise tasks", false, "lists tasks"},
	{"mise test", false, "only mise run is recognized"},

	{"turbo run test", true, "a test task"},
	{"turbo run build test lint", true, "several check tasks"},
	{"turbo test", true, "turbo TASK is turbo run TASK"},
	{"turbo run test --filter=web", true, "an attached filter"},
	{"turbo run lint -F web", true, "-F takes a value"},
	{"turbo run test --continue --concurrency 4", true, "value and boolean options"},
	{"turbo run test -- --coverage", true, "passthrough arguments"},
	{"turbo run test --ui stream", true, "the streaming UI"},
	{"turbo run dev", false, "a dev server"},
	{"turbo dev", false, "a dev server"},
	{"turbo run build dev", false, "a second task that serves"},
	{"turbo run test --dry-run", false, "prints the plan"},
	{"turbo run test --dry=json", false, "prints the plan"},
	{"turbo run test --graph", false, "prints the graph"},
	{"turbo run test --ui tui", false, "the terminal UI"},
	{"turbo run test --ui=tui", false, "the terminal UI"},
	{"turbo run test -- --watch", false, "watch flag in passthrough arguments"},
	{"turbo watch test", false, "turbo watch re-runs forever"},
	{"turbo run", false, "no task"},
	{"turbo login", false, "a turbo command"},
	{"turbo prune web", false, "a turbo command"},

	{"nx test app", true, "a test target"},
	{"nx lint app", true, "a lint target"},
	{"nx build app --configuration=production", true, "a build target"},
	{"nx run app:test", true, "run PROJECT:TARGET"},
	{"nx run app:build:production", true, "run PROJECT:TARGET:CONFIG"},
	{"nx run-many -t test lint", true, "run-many with two targets"},
	{"nx run-many --target=test --all", true, "run-many --target="},
	{"nx run-many --targets=lint,test", true, "run-many --targets="},
	{"nx affected -t test", true, "affected -t"},
	{"nx affected:test", true, "legacy affected:TARGET"},
	{"nx test app --testFile=src/a.spec.ts", true, "executor options pass through"},
	{"npx nx test app", true, "through npx"},
	{"nx serve app", false, "a dev server"},
	{"nx dev app", false, "a dev server"},
	{"nx run app:serve", false, "a dev server"},
	{"nx run app:build:development-watch", false, "a watching configuration"},
	{"nx run-many -t test serve", false, "a target that serves"},
	{"nx test app --watch", false, "watch mode"},
	{"nx test app --ui", false, "the test runner's UI server"},
	{"nx graph", false, "opens the project graph"},
	{"nx test app --graph", false, "prints the task graph"},
	{"nx run-many -t test --tui", false, "the terminal UI"},
	{"nx run-many -t test --output-style=tui", false, "the terminal UI"},
	{"nx format:check", false, "an nx command"},
	{"nx g lib mylib", false, "a generator"},
	{"nx show projects", false, "prints data"},
	{"nx run-many --all", false, "no target"},
	{"nx e2e app", false, "not a check target name"},

	{"rake test", true, "the test task"},
	{"rake spec", true, "RSpec's task"},
	{"rake spec:models", true, "a namespaced spec task"},
	{"rake test:units", true, "a namespaced test task"},
	{"rake test TEST=test/a_test.rb", true, "an environment argument"},
	{"rake test[fast]", true, "task arguments"},
	{"rake -f Rakefile.ci test", true, "--rakefile takes a value"},
	{"rake --trace test", true, "trace"},
	{"rake lint test", true, "two check tasks"},
	{"rake", false, "the default task: unknown"},
	{"rake -T", false, "lists tasks"},
	{"rake --tasks", false, "lists tasks"},
	{"rake -D test", false, "describes tasks"},
	{"rake -P", false, "prints prerequisites"},
	{"rake -W test", false, "prints where tasks are defined"},
	{"rake -n test", false, "a dry run"},
	{"rake -e 'puts 1'", false, "evaluates code"},
	{"rake db:migrate", false, "not a check task"},
	{"rake server", false, "a server"},
	{"rake console", false, "a console"},
	{"rake release", false, "releases a gem: may prompt"},

	{"deno test", true, "deno's test runner"},
	{"deno test -A tests/", true, "permissions and paths"},
	{"deno test --allow-read --coverage=cov", true, "coverage to a directory"},
	{"deno check main.ts", true, "type checking"},
	{"deno lint", true, "the linter"},
	{"deno task test", true, "a test task"},
	{"deno task lint:fix", true, "a lint task"},
	{"deno test --watch", false, "watch mode"},
	{"deno test --inspect-brk", false, "waits for a debugger"},
	{"deno test --reporter=junit", false, "machine-readable"},
	{"deno test --reporter tap", false, "machine-readable"},
	{"deno lint --json", false, "machine-readable"},
	{"deno lint --rules", false, "lists rules"},
	{"deno task", false, "lists tasks"},
	{"deno task dev", false, "a dev server"},
	{"deno task --eval 'echo hi'", false, "runs a shell command"},
	{"deno run main.ts", false, "a program"},
	{"deno bench", false, "the numbers are the point"},

	{"cargo nextest run", true, "nextest's test run"},
	{"cargo nextest run -p mycrate", true, "a package"},
	{"cargo nextest run --workspace --profile ci", true, "a profile"},
	{"cargo +nightly nextest run", true, "a toolchain"},
	{"cargo nextest r", true, "r is run"},
	{"cargo nextest list", false, "lists tests"},
	{"cargo nextest run --no-run", false, "builds only"},
	{"cargo nextest run --message-format libtest-json", false, "machine-readable"},
	{"cargo nextest archive --archive-file a.tar.zst", false, "writes an archive"},
	{"cargo nextest show-config test-groups", false, "prints configuration"},

	{"composer test", true, "a test script"},
	{"composer run-script test", true, "run-script"},
	{"composer run lint", true, "run is run-script"},
	{"composer run-script --timeout=0 test", true, "the timeout option"},
	{"composer test -- --filter FooTest", true, "script arguments"},
	{"composer install", true, "install (unchanged)"},
	{"composer run-script --list", false, "lists scripts"},
	{"composer run-script serve", false, "a server"},
	{"composer check-platform-reqs", false, "a composer command, not a script"},
	{"composer validate", false, "a composer command"},
	{"composer update", false, "not in the table"},

	{"bun test", true, "bun's test runner"},
	{"bun test --coverage", true, "coverage"},
	{"bun test --watch", false, "watch mode"},
	{"npm run test:unit", true, "a test:* script"},
	{"pnpm test:e2e", true, "a test:* script by bare name"},
	{"yarn lint:fix", true, "a lint:* script"},
	{"npm run check-types", true, "a check* script"},
	{"npm run typecheck:app", true, "a typecheck* script"},
	{"pnpm run build:prod", true, "a build* script"},
	{"npm run testonly", true, "a test* script"},
	{"npm run dev", false, "a dev server"},
	{"pnpm start", false, "a server"},
	{"npm run serve:api", false, "a server"},
	{"yarn watch:css", false, "a watcher"},
	{"npm run preview", false, "a preview server"},
	{"npm run build:watch", false, "a watching build"},

	{"nx run-many --targets test serve", false, "a second target that serves (--targets takes several words)"},
	{"nx run-many --target test serve", false, "--target is the same array option"},
	{"nx run-many --targets=test serve", false, "an attached first value, then more words"},
	{"nx affected --targets lint dev", false, "affected: a second target that serves"},
	{"nx run-many -t test -t serve", false, "a second -t"},
	{"nx run-many -t=test,lint", true, "an attached comma list"},
	{"nx run-many --targets test lint --parallel=3", true, "two check targets, then an option"},

	{"just testserver", false, "starts a test server"},
	{"task testnet", false, "starts a local chain"},
	{"just buildwatch", false, "a watching build"},
	{"mise run checkout", false, "not a check"},
	{"rake compiled", false, "not a check"},
	{"turbo run tests", true, "tests is a check word"},
	{"just test-integration", true, "test, then a qualifier"},
	{"just check_types", true, "check, then a qualifier"},
	{"composer run-script cs-check", true, "a style check"},

	{"just $RECIPE_TEST", false, "the recipe is a variable's value"},
	{"task ${TASK:-test}", false, "the task is a variable's value"},
	{"just test $ARGS", false, "the arguments may be --watch"},
	{"mise run test `cat args`", false, "command substitution in the arguments"},
	{"nx test app $FLAGS", false, "executor options from a variable"},
}

func TestSupportedRunners(t *testing.T) {
	if len(runnerRows) < 40 {
		t.Fatalf("only %d rows", len(runnerRows))
	}
	seen := map[string]bool{}
	for _, r := range runnerRows {
		if seen[r.cmd] {
			t.Errorf("%q listed twice", r.cmd)
		}
		seen[r.cmd] = true
		if got := hook.Supported(strings.Fields(strings.ReplaceAll(r.cmd, "'", ""))); got != r.want {
			t.Errorf("Supported(%q) = %v, want %v (%s)", r.cmd, got, r.want, r.why)
		}
	}
}

func TestRewriteRunners(t *testing.T) {
	const same = "\x00same"
	cases := []struct{ in, want string }{
		{`just test`, `lx just test`},
		{`cd api && task test`, `cd api && lx task test`},
		{`mise run test ::: lint`, `lx mise run test ::: lint`},
		{`turbo run test --filter=web`, `lx turbo run test --filter=web`},
		{`npx nx test app`, `lx npx nx test app`},
		{`nx run app:test`, `lx nx run app:test`},
		{`bundle exec rake test`, same},
		{`rake test TEST=test/a_test.rb`, `lx rake test TEST=test/a_test.rb`},
		{`deno test -A`, `lx deno test -A`},
		{`cargo nextest run`, `lx cargo nextest run`},
		{`composer test`, `lx composer test`},
		{`CI=1 just test`, `CI=1 lx just test`},
		{`timeout 600 task test`, `timeout 600 lx task test`},
		{`just dev`, same},
		{`just test | tail -20`, same},
		{`task --watch test`, same},
		{`turbo run dev`, same},
		{`nx serve app`, same},
		{`mise run`, same},
		{`rake -T`, same},
		{`deno task dev`, same},
		{`LX_RAW=1 just test`, same},

		{`nx run-many --targets test serve`, same},
		{`npx nx affected --target=test dev`, same},
		{`just "$RECIPE"`, same},
		{`just test $ARGS`, same},
		{`just testserver`, same},
		{`cargo nextest run 2>&1`, `lx cargo nextest run 2>&1`},
	}
	for _, c := range cases {
		got, ok := hook.Rewrite(c.in)
		want, wantOK := c.want, true
		if c.want == same {
			want, wantOK = c.in, false
		}
		if got != want || ok != wantOK {
			t.Errorf("Rewrite(%q)\n got  %q ok=%v\n want %q ok=%v (reason: %s)",
				c.in, got, ok, want, wantOK, hook.Inspect(c.in).Reason)
		}
	}
}
